# Generated by Django 5.0.4 on 2024-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mp', '0002_playlistentry_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30)),
                ('music_dir', models.CharField(max_length=30)),
                ('_starring', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistEntry',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
