# Generated by Django 5.0.4 on 2024-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mp', '0004_rename_songs_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='_starring',
            new_name='star_ring',
        ),
    ]
